apiVersion: v1
kind: Pod
metadata:
  name: ressource-management
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name: MYSQL_PASSWORD
      value: "password"
    resources:
      requests:
        memory: "16Gi"
        cpu: "250m"
      limits:
        memory: "32Gi"
        cpu: "500m"
  - name: wp
    image: wordpress
    resources:
      requests:
        memory: "16Gi"
        cpu: "250m"
      limits:
        memory: "32Gi"
        cpu: "500m"
