apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busyboxlab
  name: busyboxlab
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: busyboxlab
    resources: {}
    readinessProbe:
      exec:
        command:
        - cat
        - /etc/hosts
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
