apiVersion: v1
kind: Pod 
metadata:
  namespace: secret
  name: secretapp
spec:
  restartPolicy: "OnFailure"
  containers:
  - name: secretapp-pod
    image: busybox
    command: ["sleep","3600"]
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "128Mi"