apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: old-deployment
    tesnet: canary
  name: old-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: old-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: old-deployment
        testnet: canary
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
        - name: config-volume
          configMap:
            name: old-cm

